resolver:  nightly-2018-06-28

packages:
 - '.'
 - location:
      git: git@github.com:tolysz/aeson
      commit: b28eaf5a811013b34eba289f8cf4a3b8b26e74db
   extra-dep: true
# - location:
#      git: git@github.com:tolysz/http-client-extra
#      commit: 0e9ab80975724867cc0391b9eca5e665391908ef
#   extra-dep: true

extra-deps:
- possible-0.1.0.5
- http-client-extra-0.1.3.0

flags: {}

extra-package-dbs: []

