resolver: lts-7.21

packages:
 - '.'
 - location:
      git: git@github.com:tolysz/aeson
      commit: 0521fe40034a81276d481b65a5a5804e18f21eea
   extra-dep: true
 - location:
      git: git@github.com:tolysz/http-client-extra
      commit: b556857719c69bf4e12c81f388d9c9ff4ebad4d4
   extra-dep: true

extra-deps:
- possible-0.1.0.5
flags: {}

extra-package-dbs: []

